# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARtique' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARtique
  pod 'SnapKit', '~> 5.0.1'
  pod 'Then', '~> 2.7.0'
  pod 'Tabman', '~> 2.9'
  pod 'PhotoCropper'
  pod 'DynamicBottomSheet'
  pod 'Moya'
  pod 'Kingfisher', '~> 7.0'
  pod 'lottie-ios'

  # Rx
  pod 'RxSwift', '< 6.2.0'
  pod 'RxCocoa', '< 6.2.0'
  pod "RxGesture"

  # Kakaotalk
  pod 'KakaoSDKUser', '~> 2.8.6'
  pod 'KakaoSDKAuth', '~> 2.8.6'
end
